install.packages("tidyverse")
install.packages("usmap")
install.packages("RColorBrewer")
install.packages("rio")
install.packages("lubridate")
install.packages("httr")
install.packages("patchwork")
install.packages("sf", configure.args = "--with-proj-lib=/usr/local/lib/")
install.packages("zoo")
install.packages("scales")
install.packages("rtweet")
install.packages("png")
