# install.packages("devtools")
# install.packages("rgeos", repos="http://R-Forge.R-project.org", type="source")
# install.packages("rgdal", repos="http://R-Forge.R-project.org", type="source")
# library(devtools)
# install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")

install.packages("tidyverse")
install.packages("usmap")
install.packages("RColorBrewer")
install.packages("rio")
install.packages("lubridate")
install.packages("cowplot")
install.packages("httr")
install.packages("patchwork")
#install.packages("sf", configure.args = "--with-proj-lib=/usr/local/lib/")
install.packages("sf")
install.packages("zoo")
install.packages("scales")
install.packages("rtweet")
install.packages("rtoot")
install.packages("png")

update.packages(ask = FALSE,
                checkBuilt = TRUE)

