install.packages("remotes")
remotes::install_deps(dependencies = TRUE, type="binary")
install.packages("tidyverse")
install.packages("usmap")
install.packages("RColorBrewer")
install.packages("rio")
install.packages("lubridate")
install.packages("httr")
install.packages("patchwork")
install.packages("sf", type = "binary")
install.packages("zoo")
install.packages("scales")
install.packages("rtweet")
install.packages("png")
