name: autochart

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  push:
    paths:
      - 'gh_action.R'

jobs:
  run-cdc_data:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
          
      - name: Restore R package cache
        id: cache-r-packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('install-packages.R') }}-1
          
          
      - name: Install gdal pt1
        run: brew install pkg-config

      - name: Install gdal pt2
        run: brew install gdal proj geos 
          
      - name: Install packages
        if: steps.cache-r-packages.outputs.cache-hit != 'true' 
        run: R -e 'source("install-packages.R", echo = TRUE)'
        
      - name: Run script
        run: Rscript gh_action.R
        
      # Add new files in data folder, commit along with other modified files, push
      - name: Commit and push if it changed
        run: |-
          git config user.name "autochart"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
